name: bhavya_giniya_portfolio
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.1.5
  gap: ^3.0.1
  get: ^4.7.2
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/png/ic_image.png"


flutter:

  uses-material-design: true

  assets:
    - assets/png/
    - assets/svg/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans_18pt-Bold.ttf
        - asset: assets/fonts/DMSans_18pt-ExtraBold.ttf
        - asset: assets/fonts/DMSans_18pt-Medium.ttf
        - asset: assets/fonts/DMSans_24pt-Regular.ttf
        - asset: assets/fonts/DMSans_24pt-SemiBold.ttf

